const SERVER_PORT = 3000;

const TICK_RATE = 20;
const TICK_INTERVAL = 1000 / TICK_RATE;

const WORLD_SIZE = 800;
const PLAYER_SIZE = 20;
const PLAYER_SPEED = 180;
const BULLET_SPEED = 420;
const BULLET_LENGTH = 18;
const BULLET_RADIUS = 3;
const BULLET_DAMAGE = 10;
const BULLET_MAX_DISTANCE = 520;
const SHOOT_INTERVAL_MS = 180;

module.exports = {
  SERVER_PORT,
  TICK_RATE,
  TICK_INTERVAL,
  WORLD_SIZE,
  PLAYER_SIZE,
  PLAYER_SPEED,
  BULLET_SPEED,
  BULLET_LENGTH,
  BULLET_RADIUS,
  BULLET_DAMAGE,
  BULLET_MAX_DISTANCE,
  SHOOT_INTERVAL_MS,
};
